### ISSUE TITLE
Doesn't work with autolayout.

### ISSUE THREAD

**Issue by kenancasey** [zsy78191/XXXTabbarController#2]
The static width makes it incompatible with iPhone 6/6s and landscape orientations. 

![screen shot 2016-07-29 at 1 47 42 pm](https://cloud.githubusercontent.com/assets/315883/17259903/3986fac4-5593-11e6-8557-0ccfef94cbba.png)

**Comment by zsy78191** [comment]
Try use left 、 right and bottom and height instead of static width.
